// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjGmiGK7Qx9t1MCz9DsnsB9LebwqdTFfs',
    appId: '1:63834150898:web:ecc5201d278ade43e5fd6b',
    messagingSenderId: '63834150898',
    projectId: 'backend-service-dd781',
    authDomain: 'backend-service-dd781.firebaseapp.com',
    databaseURL: 'https://backend-service-dd781-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-service-dd781.firebasestorage.app',
    measurementId: 'G-07XRYL9G3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-52XZ0Tw1HHAUOnVcUnLpbGcmpOngQcE',
    appId: '1:63834150898:android:eea28cbb48a6718be5fd6b',
    messagingSenderId: '63834150898',
    projectId: 'backend-service-dd781',
    databaseURL: 'https://backend-service-dd781-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-service-dd781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2FEG8-_rA3XOw7v43cObAPC3ZcQuzfw',
    appId: '1:63834150898:ios:67960bd720935ceae5fd6b',
    messagingSenderId: '63834150898',
    projectId: 'backend-service-dd781',
    databaseURL: 'https://backend-service-dd781-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-service-dd781.firebasestorage.app',
    iosBundleId: 'com.example.isMbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF2FEG8-_rA3XOw7v43cObAPC3ZcQuzfw',
    appId: '1:63834150898:ios:67960bd720935ceae5fd6b',
    messagingSenderId: '63834150898',
    projectId: 'backend-service-dd781',
    databaseURL: 'https://backend-service-dd781-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-service-dd781.firebasestorage.app',
    iosBundleId: 'com.example.isMbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjGmiGK7Qx9t1MCz9DsnsB9LebwqdTFfs',
    appId: '1:63834150898:web:d3064ff40afd3778e5fd6b',
    messagingSenderId: '63834150898',
    projectId: 'backend-service-dd781',
    authDomain: 'backend-service-dd781.firebaseapp.com',
    databaseURL: 'https://backend-service-dd781-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-service-dd781.firebasestorage.app',
    measurementId: 'G-6516FZBYEL',
  );
}
